version: "3"

services:
  gearman:
    image: legacyphp/gearman:latest
    container_name: 'gearman'
    restart: unless-stopped
    tty: true
    environment:
      - 'TZ=UTC'
      - 'VERBOSE=DEBUG'
    networks:
      - network1

  gearman-ui:
    image: 'legacyphp/gearman-ui:latest'
    container_name: 'gearman-ui'
    restart: unless-stopped
    tty: true
    ports:
      - '8081:80'
    environment:
      - 'TZ=UTC'
      - 'GEARMAN_SERVERS=Gearman#1:gearman:4730'
    networks:
      - network1

networks:
  network1:
    driver: bridge
