version: "3.4"

services:

  thumbor:
    container_name: 'thumbor'
    build:
      context: ./
      dockerfile: ./docker/thumbor-7.3/Dockerfile-alpine
    tty: true
    ports:
      - '8888:8888'
    environment:
      - 'TZ=Europe/Moscow'

      - 'PORT=8888'
      - 'LOG_LEVEL=warning'


      - 'LOADER=thumbor_aws.loader'
      - 'AWS_LOADER_REGION_NAME=local'
      - 'AWS_LOADER_BUCKET_NAME=img'
      - 'AWS_LOADER_S3_ACCESS_KEY_ID=admin'
      - 'AWS_LOADER_S3_SECRET_ACCESS_KEY=12345678'
      - 'AWS_LOADER_S3_ENDPOINT_URL=http://minio:9000/'

#      - 'LOADER=thumbor.loaders.http_loader'
#      - 'STORAGE=thumbor_aws.storage'
#      - 'AWS_STORAGE_BUCKET_NAME=img-cache'
#      - 'AWS_STORAGE_S3_ACCESS_KEY_ID=admin'
#      - 'AWS_STORAGE_S3_SECRET_ACCESS_KEY=12345678'
#      - 'AWS_STORAGE_S3_ENDPOINT_URL=http://minio:9000/'


      - 'RESULT_STORAGE=thumbor_aws.result_storage'
      - 'AWS_RESULT_STORAGE_BUCKET_NAME=img-cache'
      - 'AWS_RESULT_STORAGE_S3_ACCESS_KEY_ID=admin'
      - 'AWS_RESULT_STORAGE_S3_SECRET_ACCESS_KEY=12345678'
      - 'AWS_RESULT_STORAGE_S3_ENDPOINT_URL=http://minio:9000/'
      - 'AWS_RESULT_STORAGE_ROOT_PATH=zz'

      - 'RESULT_STORAGE_STORES_UNSAFE=True'
#      # Expiration in seconds of generated images in the result storage. (2629746 is a month is seconds)
#      - 'RESULT_STORAGE_EXPIRATION_SECONDS=2629746'
#
#      - 'HTTP_LOADER_VALIDATE_CERTS=False'
#
#      - 'RESPECT_ORIENTATION=True'
#      - 'QUALITY=80'
#      - 'MAX_AGE=86400' # 86400 is a day of caching (number of seconds)
#      - 'AUTO_PNG_TO_JPG=True'
#
#      - 'ALLOW_UNSAFE_URL=True'
#      - 'SECURITY_KEY=31337'
    depends_on:
      - minio
    networks:
      - network1

  # Do NOT use MINIO_DOMAIN or MINIO_SERVER_URL with Traefik.
  # All Routing is done by proxy server (nginx, traefik), just tell minio where to redirect to.
  # - MINIO_BROWSER_REDIRECT_URL=http://stash.localhost
  minio:
    image: bitnami/minio:latest
    container_name: 'minio'
    restart: unless-stopped
    tty: true
    environment:
      - 'TZ=Europe/Moscow'
      - 'MINIO_ROOT_USER=admin'
      - 'MINIO_ROOT_PASSWORD=12345678'
      - 'MINIO_DEFAULT_BUCKETS=img:none,img-cache:none'
      - 'MINIO_BROWSER=on'
      - 'CONSOLE_SECURE_TLS_REDIRECT=off'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    networks:
      - network1

networks:
  network1:
    driver: bridge

volumes:
  minio_data:
    driver: local

