name: Build [latest] docker image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  schedule:
    - cron: "0 0 * * 6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gearman_version: [ '1.1.20' ]
        gearman_version_minor: [ '1.1' ]

    steps:
      - name: Prepare env variables
        run: |
          echo "BUILD_DATE=$(TZ=':UTC' date +'%Y-%m-%d %H:%M:%S (%Z)')" >> ${GITHUB_ENV}
          echo "BUILD_FINGERPRINT=${GITHUB_SHA::7}" >> ${GITHUB_ENV}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build images and push to registry
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          cache-from: type=gha, scope=${{ github.workflow }}-${{ matrix.gearman_version }}
          cache-to: type=gha, scope=${{ github.workflow }}-${{ matrix.gearman_version }}, mode=max
          context: .
          file: ./docker/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_FINGERPRINT=${{ env.BUILD_FINGERPRINT }}
            GEARMAN_VERSION=${{ matrix.gearman_version }}
          tags: |
            legacyphp/gearman:${{ matrix.gearman_version }}
            legacyphp/gearman:${{ matrix.gearman_version_minor }}
            legacyphp/gearman:latest
            ghcr.io/phplegacy/gearman-docker:${{ matrix.gearman_version }}
            ghcr.io/phplegacy/gearman-docker:${{ matrix.gearman_version_minor }}
            ghcr.io/phplegacy/gearman-docker:latest
          pull: true
          push: true


  Update-Docker-Hub-repo-description:
    name: Update Docker Hub repo description
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update Docker Hub repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: legacyphp/gearman
          #short-description: ${{ github.event.repository.description }}
